[yongin_kakao]
title = "용인시 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_SxkxoYxl"
entrySelector = "div.wrap_post"
titleSelector = "p.desc_post"
linkSelector = "span.txt_time a"
contentSelector = "p.desc_post"
DateSelector = "span.txt_time a"
DateFormat = "MM월 dd일 a hh:mm"
imageSelector = "a.link_thumb div.wrap_thumb"
waitUntil = "networkidle"

[yongin_linktree]
title = "용인시 ─ 링크트리"
url = "https://linktr.ee/yicity"
entrySelector = "div.sc-dQppl.jjdMus"
titleSelector = "p[class='sc-hBEYos Button__StyledText-sc-uh5tyw-0 cqgIKE rsIfq']"
linkSelector = "a[class='sc-hHftDr StyledButton-sc-686c3k-0 egoGPQ dLjCyh']"
