[yongin_kakao]
title = "용인시 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_SxkxoYxl"
entrySelector = "div.wrap_post"
titleSelector = "p.desc_post"
linkSelector = "span.txt_time a"
contentSelector = "p.desc_post"
DateSelector = "span.txt_time a"
DateFormat = "MM월 dd일 a hh:mm"
imageSelector = "a.link_thumb div.wrap_thumb"
waitUntil = "networkidle"